version: '3'

services:
  test:
    build: .
    command: go test ./...
    environment:
      - DB_HOST=test_db
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=test_db
      - DB_PORT=5432
    depends_on:
      - test_db
  db:
    image: postgres:12
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: app_db
    ports:
      - "5432:5432"
  test_db:
    image: postgres:12
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: test_db
    ports:
      - "5432:5432"
  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=app_db
    depends_on:
      - db
  